---
- name: Install Keepalived
  apt:
    name: keepalived
    state: present

- name: Install psmisc
  apt:
    name: psmisc
    state: present

- name: Configure keepalived.conf
  ansible.builtin.template:
    src: keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: 644

- name: Restart Keepalived service
  ansible.builtin.service:
    name: keepalived
    state: restarted